"use strict";
//电梯定义

const mongoose = require("mongoose");

//Schema
const Schema = mongoose.Schema;

const halfMonthMaintainSchema = new Schema({
    liftId:String,
    maintain_id:String,
    auditStatus:String,//审核状态 1 未审核 2 审核通过 3 审核未通过
    startDate:Date,
    maintainContent:{
        num1:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//机房、轮滑间环境
        num2:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//手动紧急操作装置
        num3:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//驱动主机	
        num4:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器个销轴部位
        num5:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器间隙
        num6:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器作为轿厢意外移动保护装置制停子系统时的自监测
        num7:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//编码器	
        num8:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//限速器各销轴部位
        num9:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门和桥门旁路装置
        num10:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//紧急电动运行
        num11:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//桥顶
        num12:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//桥顶检修、急停开关
        num13:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//导靴油杯
        num14:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//对重/平衡重块及其压板	
        num15:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//井道照明
        num16:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢照明、风扇、应急灯
        num17:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢检修、停止装置
        num18:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿内报警装置、对讲系统
        num19:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿内显示、指令按钮、IC卡系统
        num20:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿门防撞击保护（安全触板、光幕等）
        num21:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿门门锁电器触点
        num22:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿门运行
        num23:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢平层精度
        num24:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层站召唤、楼层显示
        num25:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门地坎
        num26:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门自动关门装置
        num27:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门门锁自动复位
        num28:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门门锁电器触点
        num29:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门锁紧元件啮合深度
        num30:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//底坑环境
        num31:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//底坑停止装置
        num32:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        }//轿内合格证、报修电话、乘梯说明
    }
})
const quarterlySchema = new Schema({
    liftId:String,
    startDate:Date,
    maintain_id:String,
    auditStatus:String,
    maintainContent:{
        num1:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//减速器润滑油	
        num2:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动衬
        num3:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//编码器	
        num4:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//选层器动静触点
        num5:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//曳引轮槽、悬挂装置
        num6:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//限速器轮槽、限速器钢丝绳
        num7:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//靴衬、滚轮	
        num8:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//验证轿门轿门关闭的电气安全装置
        num9:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门/轿门传动钢丝/链条/传动带
        num10:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门门导靴
        num11:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//消防开关
        num12:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//耗能缓冲器
        num13:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        }//限速器张紧轮装置和电气安全装置
    }
})
const halfYearSchema = new Schema({
    liftId:String,
    startDate:Date,
    maintain_id:String,
    auditStatus:String,
    maintainContent:{
        num1:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//电动机、减速箱连轴螺栓
        num2:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//驱动轮、导向轮轴承部
        num3:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//曳引轮槽	
        num4:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器动作状态监测装置
        num5:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//控制柜内各接线端子
        num6:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//控制柜各仪表
        num7:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//井道、对重、轿顶各反绳轮轴承部	
        num8:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//曳引装置、补偿绳
        num9:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//绳头组合
        num10:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//限速器钢丝绳
        num11:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门、轿门门扇
        num12:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿门开门限制装置
        num13:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//对重缓冲器距离
        num14:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//补偿链（绳）与轿厢、对重接合处	
        num15:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//上下极限开关
    }
})
const yearSchema = new Schema({
    liftId:String,
    startDate:Date,
    maintain_id:String,
    auditStatus:String,
    maintainContent:{
        num1:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//减速机润滑油
        num2:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//控制柜接触器、继电器触点
        num3:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器铁芯（柱塞）	
        num4:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//制动器制动能力
        num5:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//导电回路绝缘测试
        num6:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//限速器安全钳联动试验
        num7:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//上行超速保护装置动作试验	
        num8:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢意外移动保护装置动作试验
        num9:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿顶、轿厢架、轿门及其附件安装螺栓
        num10:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢和对重/平衡重的导轨支架
        num11:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢和对重/平衡重的导轨
        num12:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//随行电缆
        num13:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//层门装置和地坎
        num14:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿厢称重装置	
        num15:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//安全钳钳座
        num16:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//轿底各安装螺栓	
        num17:{
            status:String,
            imagePath:String,
            result:String,
            tj:String,
            gh:String,
            cb1:String,
            cb2:String
        },//缓冲器
    }
})
const repaireSchema = new Schema({
    use_unit:String,
    plat:String,
    rate_weight:String,
    
})

//导出
exports.halfMonthMaintain = mongoose.model("halfMonthMaintain", halfMonthMaintainSchema, "half_month_maintain");
exports.quarterlyMaintain = mongoose.model("quarterlyMaintain", quarterlySchema, "quarterly_maintain");
exports.halfYearMaintain = mongoose.model("halfYearMaintain", halfYearSchema, "half_year_maintain");
exports.yearMaintain = mongoose.model("yearMaintain", yearSchema, "year_maintain");
exports.repaireModel = mongoose.model("repaire",repaireSchema,"repaire")
